# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - wapsinglecpnt

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to container registry
        uses: docker/login-action@v2
        with:
          registry: testerregistry.azurecr.io/
          username: ${{ secrets.AZUREAPPSERVICE_CONTAINERUSERNAME_731F24EA5B5944549CF286025783BB0B }}
          password: ${{ secrets.AZUREAPPSERVICE_CONTAINERPASSWORD_4C6C8B4F11C745CDACE984BD1E0DCF97 }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: testerregistry.azurecr.io/${{ secrets.AZUREAPPSERVICE_CONTAINERUSERNAME_731F24EA5B5944549CF286025783BB0B }}/hello-world:${{ github.sha }}
          file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    
    needs: build
    

    steps:
      
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'wapsinglecpnt'
          slot-name: 'Production'
          images: 'testerregistry.azurecr.io/${{ secrets.AZUREAPPSERVICE_CONTAINERUSERNAME_731F24EA5B5944549CF286025783BB0B }}/hello-world:${{ github.sha }}'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_8120121F95CC47D2876B200FA320C15B }}